# Copyright (c) 2020-2021, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.
%YAML 1.2
---
name: tx
components:
- name: tensor
  type: nvidia::gxf::DoubleBufferTransmitter
  parameters:
    capacity: 25
- name: allocator
  type: nvidia::gxf::UnboundedAllocator
- type: nvidia::gxf::DownstreamReceptiveSchedulingTerm
  parameters:
    transmitter: tensor
    min_size: 1
- type: nvidia::isaac_ros::RosBridgeTensorSubscriber
  parameters:
    signal: tensor
    allocator: allocator
    topic_name: tensor_pub
    storage_type: 1
    qos: 10
---
name: rx
components:
- name: tensor
  type: nvidia::gxf::DoubleBufferReceiver
  parameters:
    capacity: 25
- type: nvidia::gxf::MessageAvailableSchedulingTerm
  parameters:
    receiver: tensor
    min_size: 1
- type: nvidia::isaac_ros::RosBridgeTensorPublisher
  parameters:
    signal: tensor
    topic_name: ping
    qos: 1000
---
name: connections
components:
- type: nvidia::gxf::Connection
  parameters:
    source: tx/tensor
    target: rx/tensor
---
name: scheduler
components:
- name: clock
  type: nvidia::gxf::RealtimeClock
- type: nvidia::gxf::GreedyScheduler
  parameters:
    max_duration_ms: 1000000
    clock: clock
- type: nvidia::gxf::JobStatistics
  parameters:
    clock: clock
