ARG BASE_IMAGE
FROM ${BASE_IMAGE}

RUN apt-get update && apt-get install -y gir1.2-gstreamer-1.0 \
	gir1.2-gst-plugins-base-1.0 \
	libgstreamer1.0-dev \
	libgstreamer-plugins-base1.0-dev \
	libgeographic-dev \
&& rm -rf /var/lib/apt/lists/* \
&& apt-get clean \
&& python3 -m pip install -U \
        crc \
        pyserial \
        numpy==1.20 \
        pytransform3d
